### ISSUE TITLE
Documentation not OS X friendly

### ISSUE THREAD

**Issue by Janrain-Colin** [possatti/pokemonsay#1]
The documentation doesn't indicate how to get `shuf` on OS X.

```
brew install coreutils
ln -s /usr/local/bin/gshuf /usr/local/bin/shuf
```

**Comment by possatti** [comment]
I didn't understand it exactly. Are you saying you needed these two commands to make pokemonsay work on your OS X? Did you need these commands before or after installing?

I don't have a Mac, so I can't test it. But if you tell me that this is it, I will gladly add the instructions on the README.md.

Is `shuf` really necessary for pokemonsay to work? I'm saying that because I'm sure I didn't use it directly. I didn't even know this thing existed (haha). But maybe it is used by cowsay, or somewhere along the way.

And could you tell me in detail what were the steps you took in order to install it and make it work?

Thanks for the feedback.

**Comment by taylor1791** [comment]
I needed both of those commands to make it work on my system (10.11.5). I ran both of those commands afterI installed it. `shuf` is used on line 115 of `pokemonsay.sh`. `pokemon_cow=$(find $pokemon_path -name "*.cow" | shuf -n1)`.

**Comment by Janrain-Colin** [comment]
@taylor1791 ➕

**Comment by possatti** [comment]
Woww. That's true. That's how a random Pokémon is selected. Hehe. My fault. It's been so long since I don't touch these scripts that I didn't even remember. Thanks for noticing that.

I already updated the README. Thank you guys. :smile:
