### ISSUE TITLE
Port this repo to homebrew

### ISSUE THREAD

**Issue by GusGA** [possatti/pokemonsay#2]
There's any chance to install this repo via homebrew?

**Comment by possatti** [comment]
Maaan. I have no I idea how to do that. But I do understand it would make things easier for OS X people a lot. I am going to take a look at it and how to do it. But the main problem is that I don't have a Mac, so I can't test it my self.

**Comment by GusGA** [comment]
Cool, I will try to help.

**Comment by possatti** [comment]
I gotta go to work now, but I will take a look at this when I get home. If you find out what needs to be done and can submit a pull request, I would appreciate.  :smile:

**Comment by possatti** [comment]
Good news. Turns out there's a  [Homebrew Linux port](https://github.com/Linuxbrew/brew). I'm experimenting with how to create the proper Formula. And I feel like I'm getting the hang of this. But it will take some time yet.

I will probably make something similar to [cowsay's Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cowsay.rb). But for this I'll need to modify the install script (`install.sh`) a little. And I will probably start versioning this repository too.

**Comment by possatti** [comment]
cc @taylor1791 @Janrain-Colin

After quite a long long time, I think I got this to work. I don't have a Mac, so could any of you guys do a quick test on the Formula for Pokemonsay?

Make sure to uninstall pokemonsay and then try:

```sh
brew tap possatti/possatti
brew install pokemonsay
```

I hope it works. All of this is new to me, so suggestions are very welcome.

**Comment by taylor1791** [comment]
I just tried to install `pokemonsay` via brew on Sierra and it worked like a charm! Thanks for you hard work!
